# Generated by Django 5.2.15 on 2026-06-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_legacy_academic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User created'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('teacher_updated', 'Teacher updated'), ('class_created', 'Class created'), ('teacher_assigned', 'Teacher assigned'), ('student_enrolled', 'Student enrolled'), ('message_sent', 'Message sent')], max_length=50),
        ),
    ]
